### ISSUE TITLE
Request for new AppConfig failed

### ISSUE THREAD

**Issue by locle** [jamf/CertificateSDK#4]
CertificateSDK version: 1.1.0

It only works once right after the app is pushed from Jamf server, if the client cert is cleared and the app request for a new client cert again, there is a high chance that the `Progress 2 of 6. Using network: false. Error: The Operation couldn't be complete. Request for new AppConfigure failed. Request completed with identity new` error message will show up.

**Comment by macblazer** [comment]
What version of Jamf Pro is your app communicating with, and why do you need to clear the client cert?

The request for a new client cert is generally dependent upon the Jamf Pro server sending a new Managed App Config command to the device which can take several seconds.  Attempting a second request for a cert before the first completes can leave the app and the server out of sync.  This is known issue with Jamf Pro, so generally the iOS app should avoid requesting a new certificate if a certificate request is already in flight.

**Comment by locle** [comment]
@macblazer Thank you for your reply, my app is communicating with Jamf Pro 10.43.1. I followed the certificate renewal guideline from Jamf https://www.jamf.com/blog/introducing-the-jamf-certificate-sdk/ to start a new certificate request when the user login. Could it be a case that CertificateSDK request is finished at the app side but the request is still being processed at Jamf Pro server and user trigger the certificate request again?

**Comment by macblazer** [comment]
The CertificateSDK will call your delegate as it progresses through the workflow.  If you have a user interface where the user can start a request, you should disable that interface while a request is in progress.  Once the request is complete within the app, that is after your delegate gets a call to `certificate(request:completedWith:)`, then you can re-enable the user interface to request a new certificate.

If you are starting a certificate request automatically in your code (maybe during the startup sequence or when a particular view is loaded), be sure to not start a second one while the first one in still in progress.

**Comment by locle** [comment]
Yes, I had a user interface where the user can start a request, and disabled that interface while a request is in progress until my delegate gets a call to `certificate(request:completedWith:)`
